/**
 * @file Automatically generated by barrelsby.
 */

export * from "./anwser";
export * from "./instructor";
export * from "./question";
export * from "./student";
export * from "./value-objects/index";
